apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm0
  labels:
    app: nginx
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;

    events { 
        worker_connections 1024; 
    }

    http {
        server {
            listen 80;

            # Тренеры
            location /trainers/ {
                proxy_pass http://trainer-service:8086/client/;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }

            # Клиент аутентификации
            location /client/ {
                proxy_pass http://auth-service:8085/client/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }

            # Фронтенд
            location / {
                proxy_pass http://frontend:80;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                error_page 404 /index.html;
            }
        }
    }
